# Generated by Django 3.1 on 2020-08-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailabilitySlots',
            new_name='AvailabilitySlot',
        ),
    ]
